version: 0
allowPullRequests: public
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
        branches:
          - staging
          - trying
    payload:
      maxRunTime: 3600
      image: jimmycuadra/rust
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo &&
          git config advice.detachedHead false && git checkout {{event.head.sha}} &&
          cat README.md
    metadata:
      name: basic test
      description: 'will echo the readme, just to check some stuff'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
